add type DataNode to styletree
DataNode includes tag: img p b and so on
treat DataNode as a special kind of StyleNode which has no child
Error: the PyQuery object cannot be deep copied